// anime-vault/src/lib/components/AnimeRow.svelte
<script lang="ts">
  import ChevronLeft from 'lucide-svelte/icons/chevron-left';
  import ChevronRight from 'lucide-svelte/icons/chevron-right';
  import AnimeCard from './AnimeCard.svelte';
  import type { AnimeMedia } from '$lib/anilist';

  let { title, anime }: { title: string; anime: AnimeMedia[] } = $props();
  let scrollEl: HTMLDivElement;

  function scroll(dir: 'left' | 'right') {
    if (!scrollEl) return;
    scrollEl.scrollBy({ left: dir === 'left' ? -600 : 600, behavior: 'smooth' });
  }
</script>

{#if anime.length}
  <section class="row">
    <div class="header">
      <h2>{title}</h2>
      <div class="arrows">
        <button onclick={() => scroll('left')}><ChevronLeft size={18} /></button>
        <button onclick={() => scroll('right')}><ChevronRight size={18} /></button>
      </div>
    </div>
    <div class="cards" bind:this={scrollEl}>
      {#each anime as a (a.id)}
        <AnimeCard anime={a} />
      {/each}
    </div>
  </section>
{/if}

<style>
  .row { margin-bottom: 32px; padding: 0 32px; }
  .header {
    display: flex; align-items: center; justify-content: space-between;
    margin-bottom: 16px;
  }
  h2 { font-size: 20px; font-weight: 700; color: white; margin: 0; }
  .arrows { display: flex; gap: 8px; }
  .arrows button {
    width: 32px; height: 32px; border-radius: 999px;
    background: rgba(255,255,255,0.05); border: none;
    color: #9ca3af; cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    transition: all 0.2s;
  }
  .arrows button:hover { background: rgba(255,255,255,0.1); color: white; }
  .cards {
    display: flex; gap: 16px; overflow-x: auto;
    padding-bottom: 8px; scroll-behavior: smooth;
  }
  .cards::-webkit-scrollbar { display: none; }
  .cards { -ms-overflow-style: none; scrollbar-width: none; }
</style>

// anime-site/src/components/AnimeRow.tsx
// src/components/AnimeRow.tsx
"use client";
import { useRef } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import AnimeCard from "./AnimeCard";
import type { AnimeMedia } from "@/lib/anilist";

interface AnimeRowProps {
  title: string;
  anime: AnimeMedia[];
}

export default function AnimeRow({ title, anime }: AnimeRowProps) {
  const scrollRef = useRef<HTMLDivElement>(null);

  const scroll = (dir: "left" | "right") => {
    if (!scrollRef.current) return;
    const amount = dir === "left" ? -600 : 600;
    scrollRef.current.scrollBy({ left: amount, behavior: "smooth" });
  };

  if (!anime.length) return null;

  return (
    <section className="mb-8 px-8">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-white">{title}</h2>
        <div className="flex items-center gap-2">
          <button
            onClick={() => scroll("left")}
            className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-white/10 hover:text-white transition-all"
          >
            <ChevronLeft size={18} />
          </button>
          <button
            onClick={() => scroll("right")}
            className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-white/10 hover:text-white transition-all"
          >
            <ChevronRight size={18} />
          </button>
        </div>
      </div>

      {/* Cards */}
      <div
        ref={scrollRef}
        className="flex gap-4 overflow-x-auto scrollbar-hide pb-2"
      >
        {anime.map((a) => (
          <AnimeCard key={a.id} anime={a} />
        ))}
      </div>
    </section>
  );
}
