// anime-site/src/components/HeroBanner.tsx
// src/components/HeroBanner.tsx
"use client";
import { useState, useEffect } from "react";
import { Play, Info, Heart, ChevronLeft, ChevronRight, Calendar, Film } from "lucide-react";
import type { AnimeMedia } from "@/lib/anilist";

interface HeroBannerProps {
  anime: AnimeMedia[];
}

export default function HeroBanner({ anime }: HeroBannerProps) {
  const [index, setIndex] = useState(0);
  const [paused, setPaused] = useState(false);

  useEffect(() => {
    if (paused || anime.length <= 1) return;
    const timer = setInterval(() => {
      setIndex((prev) => (prev + 1) % anime.length);
    }, 8000);
    return () => clearInterval(timer);
  }, [paused, anime.length]);

  if (!anime.length) return null;

  const current = anime[index];
  const title = current.title.english || current.title.romaji;
  const banner = current.bannerImage || current.coverImage.extraLarge;
  const description = (current.description || "").replace(/<[^>]+>/g, "").slice(0, 200);

  const next = () => setIndex((prev) => (prev + 1) % anime.length);
  const prev = () => setIndex((prev) => (prev - 1 + anime.length) % anime.length);

  return (
    <div
      className="relative h-[70vh] min-h-[500px] w-full overflow-hidden"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      {/* Background */}
      <div className="absolute inset-0">
        {anime.map((a, i) => (
          <div
            key={a.id}
            className="absolute inset-0 transition-opacity duration-1000"
            style={{
              backgroundImage: `url(${a.bannerImage || a.coverImage.extraLarge})`,
              backgroundSize: "cover",
              backgroundPosition: "center 25%",
              opacity: i === index ? 1 : 0,
            }}
          />
        ))}
        {/* Gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-black via-black/60 to-transparent" />
        <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-transparent to-transparent" />
      </div>

      {/* Top bar */}
      <div className="absolute top-0 left-0 right-0 z-20 flex items-center justify-between px-8 py-5">
        {/* Search */}
        <div className="flex-1 max-w-md mx-auto">
          <div className="flex items-center gap-2 bg-black/50 backdrop-blur-md rounded-full px-5 py-2.5 border border-white/10">
            <input
              type="text"
              placeholder="Search anime..."
              className="flex-1 bg-transparent text-white text-sm placeholder-gray-400 outline-none"
            />
            <SearchIcon size={18} className="text-gray-400" />
          </div>
        </div>
        {/* Sign In */}
        <button className="flex items-center gap-2 px-5 py-2.5 rounded-full border border-white/20 text-white text-sm font-medium hover:bg-white/10 transition-all">
          Sign In
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4M10 17l5-5-5-5M15 12H3" />
          </svg>
        </button>
      </div>

      {/* Content */}
      <div className="absolute bottom-0 left-0 right-0 z-10 px-8 pb-10">
        <div className="max-w-2xl">
          {/* Title */}
          <h1 className="text-4xl md:text-5xl font-black text-white mb-3 leading-tight">
            {title?.split(" ").slice(0, -1).join(" ")}{" "}
            <span className="text-blue-500">
              {title?.split(" ").slice(-1)}
            </span>
          </h1>

          {/* Metadata */}
          <div className="flex items-center gap-4 mb-3 text-sm">
            <span className="text-green-500 font-semibold uppercase tracking-wide">
              {current.status === "RELEASING" ? "Releasing" : current.status}
            </span>
            <span className="flex items-center gap-1.5 text-gray-300">
              <Calendar size={14} />
              {current.season ? `${current.season} ${current.seasonYear}` : current.seasonYear}
            </span>
            {current.episodes && (
              <span className="flex items-center gap-1.5 text-gray-300">
                <Film size={14} />
                {current.episodes} Episodes
              </span>
            )}
          </div>

          {/* Synopsis */}
          <p className="text-gray-300/80 text-sm md:text-base mb-5 line-clamp-2">
            {description}
          </p>

          {/* Buttons */}
          <div className="flex items-center gap-3 mb-4">
            <button className="flex items-center gap-2 px-6 py-2.5 bg-white text-black font-bold rounded-md hover:bg-white/90 transition-all text-sm">
              <Play size={18} fill="currentColor" />
              Watch Now
            </button>
            <button className="w-10 h-10 flex items-center justify-center bg-white/10 backdrop-blur-md rounded-md hover:bg-white/20 transition-all">
              <Info size={18} />
            </button>
            <button className="w-10 h-10 flex items-center justify-center bg-white/10 backdrop-blur-md rounded-md hover:bg-white/20 transition-all">
              <Heart size={18} />
            </button>
          </div>

          {/* Carousel indicators */}
          <div className="flex items-center gap-2">
            {anime.map((_, i) => (
              <button
                key={i}
                onClick={() => setIndex(i)}
                className={`h-1 rounded-full transition-all ${
                  i === index ? "w-8 bg-white" : "w-4 bg-white/30"
                }`}
              />
            ))}
          </div>
        </div>
      </div>

      {/* Navigation arrows */}
      <button
        onClick={prev}
        className="absolute right-4 top-1/2 -translate-y-1/2 z-10 w-10 h-10 bg-black/40 backdrop-blur-sm rounded-full flex items-center justify-center text-white hover:bg-black/60 transition-all"
      >
        <ChevronLeft size={20} />
      </button>
      <button
        onClick={next}
        className="absolute right-4 top-1/2 -translate-y-1/2 z-10 w-10 h-10 bg-black/40 backdrop-blur-sm rounded-full flex items-center justify-center text-white hover:bg-black/60 transition-all ml-12"
      >
        <ChevronRight size={20} />
      </button>
    </div>
  );
}

function SearchIcon({ size, className }: { size: number; className?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

// anime-vault/src/lib/components/HeroBanner.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Play from 'lucide-svelte/icons/play';
  import Info from 'lucide-svelte/icons/info';
  import Heart from 'lucide-svelte/icons/heart';
  import ChevronLeft from 'lucide-svelte/icons/chevron-left';
  import ChevronRight from 'lucide-svelte/icons/chevron-right';
  import CalendarIcon from 'lucide-svelte/icons/calendar';
  import Film from 'lucide-svelte/icons/film';
  import type { AnimeMedia } from '$lib/anilist';

  let { anime }: { anime: AnimeMedia[] } = $props();
  let index = $state(0);
  let paused = $state(false);
  let timer: ReturnType<typeof setInterval>;

  $effect(() => {
    if (paused || anime.length <= 1) return;
    timer = setInterval(() => {
      index = (index + 1) % anime.length;
    }, 8000);
    return () => clearInterval(timer);
  });

  function next() { index = (index + 1) % anime.length; }
  function prev() { index = (index - 1 + anime.length) % anime.length; }

  let current = $derived(anime[index] ?? anime[0]);
  let title = $derived(current?.title?.english || current?.title?.romaji || '');
  let banner = $derived(current?.bannerImage || current?.coverImage?.extraLarge || '');
  let description = $derived((current?.description || '').replace(/<[^>]+>/g, '').slice(0, 200));
</script>

{#if current}
  <div
    class="hero"
    onmouseenter={() => (paused = true)}
    onmouseleave={() => (paused = false)}
  >
    <!-- Background layers -->
    <div class="bg-layer">
      {#each anime as a, i (a.id)}
        <div
          class="bg-image"
          style="background-image: url({a.bannerImage || a.coverImage.extraLarge}); opacity: {i === index ? 1 : 0};"
        ></div>
      {/each}
      <div class="gradient-bottom"></div>
      <div class="gradient-left"></div>
    </div>

    <!-- Top bar -->
    <div class="top-bar">
      <div class="search-bar">
        <input type="text" placeholder="Search anime..." />
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
      </div>
      <button class="sign-in">
        Sign In
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4M10 17l5-5-5-5M15 12H3" />
        </svg>
      </button>
    </div>

    <!-- Content -->
    <div class="content">
      <h1 class="title">
        {title.split(' ').slice(0, -1).join(' ')}
        <span class="accent">{title.split(' ').slice(-1)}</span>
      </h1>

      <div class="meta">
        <span class="status">{current.status === 'RELEASING' ? 'Releasing' : current.status}</span>
        <span class="meta-item">
          <CalendarIcon size={14} />
          {current.season ? `${current.season} ${current.seasonYear}` : current.seasonYear}
        </span>
        {#if current.episodes}
          <span class="meta-item">
            <Film size={14} />
            {current.episodes} Episodes
          </span>
        {/if}
      </div>

      <p class="synopsis">{description}</p>

      <div class="buttons">
        <button class="btn-primary">
          <Play size={18} fill="currentColor" />
          Watch Now
        </button>
        <button class="btn-secondary"><Info size={18} /></button>
        <button class="btn-secondary"><Heart size={18} /></button>
      </div>

      <div class="indicators">
        {#each anime as _, i (i)}
          <button
            class="indicator"
            class:active={i === index}
            onclick={() => (index = i)}
          ></button>
        {/each}
      </div>
    </div>

    <!-- Nav arrows -->
    <button class="nav-arrow" onclick={prev}><ChevronLeft size={20} /></button>
    <button class="nav-arrow right" onclick={next}><ChevronRight size={20} /></button>
  </div>
{/if}

<style>
  .hero {
    position: relative;
    height: 70vh;
    min-height: 500px;
    width: 100%;
    overflow: hidden;
  }
  .bg-layer { position: absolute; inset: 0; }
  .bg-image {
    position: absolute; inset: 0;
    background-size: cover; background-position: center 25%;
    transition: opacity 1s ease;
  }
  .gradient-bottom {
    position: absolute; inset: 0;
    background: linear-gradient(to top, #000, rgba(0,0,0,0.4) 60%, transparent);
  }
  .gradient-left {
    position: absolute; inset: 0;
    background: linear-gradient(to right, rgba(0,0,0,0.85), transparent 60%);
  }

  .top-bar {
    position: absolute; top: 0; left: 0; right: 0; z-index: 20;
    display: flex; align-items: center; justify-content: space-between;
    padding: 20px 32px;
  }
  .search-bar {
    display: flex; align-items: center; gap: 8px;
    background: rgba(0,0,0,0.5); backdrop-filter: blur(12px);
    border-radius: 999px; padding: 10px 20px;
    border: 1px solid rgba(255,255,255,0.1);
    max-width: 400px; width: 100%; margin: 0 auto;
  }
  .search-bar input {
    flex: 1; background: transparent; border: none; outline: none;
    color: white; font-size: 14px;
  }
  .search-bar input::placeholder { color: #999; }
  .sign-in {
    display: flex; align-items: center; gap: 8px;
    padding: 10px 20px; border-radius: 999px;
    border: 1px solid rgba(255,255,255,0.2);
    background: transparent; color: white; font-size: 14px;
    cursor: pointer; transition: all 0.2s;
  }
  .sign-in:hover { background: rgba(255,255,255,0.1); }

  .content {
    position: absolute; bottom: 0; left: 0; right: 0; z-index: 10;
    padding: 0 32px 40px; max-width: 640px;
  }
  .title {
    font-size: 48px; font-weight: 800; color: white; line-height: 1.1;
    margin: 0 0 12px;
  }
  .accent { color: #3b82f6; }
  .meta {
    display: flex; align-items: center; gap: 16px;
    margin-bottom: 12px; font-size: 14px;
  }
  .status {
    color: #4ade80; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.5px; font-size: 13px;
  }
  .meta-item { display: flex; align-items: center; gap: 6px; color: #d1d5db; }
  .synopsis {
    color: #9ca3af; font-size: 15px; line-height: 1.6;
    margin: 0 0 20px; max-width: 600px;
    display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical;
    overflow: hidden;
  }
  .buttons { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
  .btn-primary {
    display: flex; align-items: center; gap: 8px;
    padding: 12px 24px; background: white; color: black;
    font-weight: 700; border-radius: 8px; border: none;
    cursor: pointer; font-size: 14px; transition: all 0.2s;
  }
  .btn-primary:hover { opacity: 0.9; }
  .btn-secondary {
    width: 40px; height: 40px; border-radius: 8px;
    background: rgba(255,255,255,0.1); backdrop-filter: blur(12px);
    border: 1px solid rgba(255,255,255,0.1); color: white;
    cursor: pointer; display: flex; align-items: center; justify-content: center;
    transition: all 0.2s;
  }
  .btn-secondary:hover { background: rgba(255,255,255,0.2); }
  .indicators { display: flex; align-items: center; gap: 8px; }
  .indicator {
    height: 3px; border-radius: 999px; border: none;
    background: rgba(255,255,255,0.3); width: 16px; cursor: pointer;
    transition: all 0.3s;
  }
  .indicator.active { background: white; width: 32px; }

  .nav-arrow {
    position: absolute; right: 16px; top: 50%; transform: translateY(-50%);
    z-index: 10; width: 40px; height: 40px; border-radius: 999px;
    background: rgba(0,0,0,0.4); backdrop-filter: blur(8px);
    border: none; color: white; cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    transition: all 0.2s;
  }
  .nav-arrow:hover { background: rgba(0,0,0,0.6); }
  .nav-arrow.right { right: 16px; }
  .nav-arrow:not(.right) { right: auto; left: calc(100% - 56px); }
</style>
